# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emu_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 613)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.reactor_status = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.reactor_status.sizePolicy().hasHeightForWidth())
        self.reactor_status.setSizePolicy(sizePolicy)
        self.reactor_status.setObjectName("reactor_status")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.reactor_status)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tfbar = QtWidgets.QWidget(self.reactor_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfbar.sizePolicy().hasHeightForWidth())
        self.tfbar.setSizePolicy(sizePolicy)
        self.tfbar.setObjectName("tfbar")
        self.gridLayout = QtWidgets.QGridLayout(self.tfbar)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar_2 = QtWidgets.QProgressBar(self.tfbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.progressBar_2.sizePolicy().hasHeightForWidth())
        self.progressBar_2.setSizePolicy(sizePolicy)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 1, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.tfbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 10.1)
        self.lcdNumber.setProperty("intValue", 10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 2, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tfbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber_2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_2.setDigitCount(10)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tfbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tfbar)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tfbar)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.tfbar)
        self.detail_status = QtWidgets.QFrame(self.reactor_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detail_status.sizePolicy().hasHeightForWidth())
        self.detail_status.setSizePolicy(sizePolicy)
        self.detail_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detail_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detail_status.setObjectName("detail_status")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.detail_status)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.detail_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.progressBar_5 = QtWidgets.QProgressBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_5.sizePolicy().hasHeightForWidth())
        self.progressBar_5.setSizePolicy(sizePolicy)
        self.progressBar_5.setMaximum(10000000)
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setTextVisible(False)
        self.progressBar_5.setObjectName("progressBar_5")
        self.gridLayout_3.addWidget(self.progressBar_5, 0, 1, 1, 1)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber_5.sizePolicy().hasHeightForWidth())
        self.lcdNumber_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setDigitCount(10)
        self.lcdNumber_5.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_5.setProperty("value", 10.0)
        self.lcdNumber_5.setProperty("intValue", 10)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.gridLayout_3.addWidget(self.lcdNumber_5, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.progressBar_6 = QtWidgets.QProgressBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_6.sizePolicy().hasHeightForWidth())
        self.progressBar_6.setSizePolicy(sizePolicy)
        self.progressBar_6.setMaximum(1000)
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setTextVisible(False)
        self.progressBar_6.setObjectName("progressBar_6")
        self.gridLayout_3.addWidget(self.progressBar_6, 1, 1, 1, 1)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber_7.sizePolicy().hasHeightForWidth())
        self.lcdNumber_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_7.setFont(font)
        self.lcdNumber_7.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_7.setSmallDecimalPoint(False)
        self.lcdNumber_7.setDigitCount(10)
        self.lcdNumber_7.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_7.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_7.setProperty("value", 10.0)
        self.lcdNumber_7.setProperty("intValue", 10)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.gridLayout_3.addWidget(self.lcdNumber_7, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.progressBar_7 = QtWidgets.QProgressBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_7.sizePolicy().hasHeightForWidth())
        self.progressBar_7.setSizePolicy(sizePolicy)
        self.progressBar_7.setMaximum(1000)
        self.progressBar_7.setProperty("value", 24)
        self.progressBar_7.setTextVisible(False)
        self.progressBar_7.setObjectName("progressBar_7")
        self.gridLayout_3.addWidget(self.progressBar_7, 2, 1, 1, 1)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber_8.sizePolicy().hasHeightForWidth())
        self.lcdNumber_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_8.setFont(font)
        self.lcdNumber_8.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_8.setSmallDecimalPoint(False)
        self.lcdNumber_8.setDigitCount(10)
        self.lcdNumber_8.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_8.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_8.setProperty("value", 10.0)
        self.lcdNumber_8.setProperty("intValue", 10)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.gridLayout_3.addWidget(self.lcdNumber_8, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.progressBar_8 = QtWidgets.QProgressBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_8.sizePolicy().hasHeightForWidth())
        self.progressBar_8.setSizePolicy(sizePolicy)
        self.progressBar_8.setMaximum(1000)
        self.progressBar_8.setProperty("value", 24)
        self.progressBar_8.setTextVisible(False)
        self.progressBar_8.setObjectName("progressBar_8")
        self.gridLayout_3.addWidget(self.progressBar_8, 3, 1, 1, 1)
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber_9.sizePolicy().hasHeightForWidth())
        self.lcdNumber_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_9.setFont(font)
        self.lcdNumber_9.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_9.setSmallDecimalPoint(False)
        self.lcdNumber_9.setDigitCount(10)
        self.lcdNumber_9.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_9.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_9.setProperty("value", 10.0)
        self.lcdNumber_9.setProperty("intValue", 10)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.gridLayout_3.addWidget(self.lcdNumber_9, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.progressBar_9 = QtWidgets.QProgressBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_9.sizePolicy().hasHeightForWidth())
        self.progressBar_9.setSizePolicy(sizePolicy)
        self.progressBar_9.setMaximum(1000)
        self.progressBar_9.setProperty("value", 24)
        self.progressBar_9.setTextVisible(False)
        self.progressBar_9.setObjectName("progressBar_9")
        self.gridLayout_3.addWidget(self.progressBar_9, 4, 1, 1, 1)
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber_10.sizePolicy().hasHeightForWidth())
        self.lcdNumber_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_10.setFont(font)
        self.lcdNumber_10.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_10.setSmallDecimalPoint(False)
        self.lcdNumber_10.setDigitCount(10)
        self.lcdNumber_10.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_10.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_10.setProperty("value", 10.0)
        self.lcdNumber_10.setProperty("intValue", 10)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.gridLayout_3.addWidget(self.lcdNumber_10, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 0, 1, 1)
        self.progressBar_15 = QtWidgets.QProgressBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_15.sizePolicy().hasHeightForWidth())
        self.progressBar_15.setSizePolicy(sizePolicy)
        self.progressBar_15.setMaximum(1000)
        self.progressBar_15.setProperty("value", 24)
        self.progressBar_15.setTextVisible(False)
        self.progressBar_15.setObjectName("progressBar_15")
        self.gridLayout_3.addWidget(self.progressBar_15, 5, 1, 1, 1)
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber_11.sizePolicy().hasHeightForWidth())
        self.lcdNumber_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_11.setFont(font)
        self.lcdNumber_11.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_11.setSmallDecimalPoint(False)
        self.lcdNumber_11.setDigitCount(10)
        self.lcdNumber_11.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_11.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_11.setProperty("value", 10.0)
        self.lcdNumber_11.setProperty("intValue", 10)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.gridLayout_3.addWidget(self.lcdNumber_11, 5, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.detail_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.radioButton = QtWidgets.QRadioButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setText("")
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_4.addWidget(self.radioButton)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.detail_status)
        self.sfbar = QtWidgets.QWidget(self.reactor_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sfbar.sizePolicy().hasHeightForWidth())
        self.sfbar.setSizePolicy(sizePolicy)
        self.sfbar.setObjectName("sfbar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sfbar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.sfbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.progressBar_3.sizePolicy().hasHeightForWidth())
        self.progressBar_3.setSizePolicy(sizePolicy)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout_2.addWidget(self.progressBar_3, 1, 1, 1, 1)
        self.progressBar_4 = QtWidgets.QProgressBar(self.sfbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.progressBar_4.sizePolicy().hasHeightForWidth())
        self.progressBar_4.setSizePolicy(sizePolicy)
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_4.setObjectName("progressBar_4")
        self.gridLayout_2.addWidget(self.progressBar_4, 1, 0, 1, 1)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.sfbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber_4.sizePolicy().hasHeightForWidth())
        self.lcdNumber_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_4.setDigitCount(10)
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout_2.addWidget(self.lcdNumber_4, 2, 1, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.sfbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lcdNumber_3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_3.setDigitCount(10)
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout_2.addWidget(self.lcdNumber_3, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.sfbar)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.sfbar)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.sfbar)
        self.verticalLayout.addWidget(self.reactor_status)
        self.reactor_control = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.reactor_control.sizePolicy().hasHeightForWidth())
        self.reactor_control.setSizePolicy(sizePolicy)
        self.reactor_control.setObjectName("reactor_control")
        self.verticalLayout.addWidget(self.reactor_control)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_21.setText(_translate("MainWindow", "Temperature"))
        self.label_22.setText(_translate("MainWindow", "Field Strength"))
        self.label.setText(_translate("MainWindow", "Fuel Conversion Rate"))
        self.progressBar_5.setFormat(_translate("MainWindow", "%v"))
        self.label_2.setText(_translate("MainWindow", "Generation Rate"))
        self.progressBar_6.setFormat(_translate("MainWindow", "%v"))
        self.label_3.setText(_translate("MainWindow", "Field Drain Rate"))
        self.progressBar_7.setFormat(_translate("MainWindow", "%v"))
        self.label_4.setText(_translate("MainWindow", "Max Field Strength"))
        self.progressBar_8.setFormat(_translate("MainWindow", "%v"))
        self.label_5.setText(_translate("MainWindow", "Max Fuel Conversion"))
        self.progressBar_9.setFormat(_translate("MainWindow", "%v"))
        self.label_11.setText(_translate("MainWindow", "Max Energy Saturation"))
        self.progressBar_15.setFormat(_translate("MainWindow", "%v"))
        self.label_18.setText(_translate("MainWindow", "Reactor Status："))
        self.label_19.setText(_translate("MainWindow", "Invalid"))
        self.label_20.setText(_translate("MainWindow", "Failsafe Mode"))
        self.label_23.setText(_translate("MainWindow", "Energy Saturation"))
        self.label_24.setText(_translate("MainWindow", "Fuel Conversion"))
